// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ0WmxnsLvgGoFhVmviIm4iDZsWEdYrJ4',
    appId: '1:179711894926:web:4e41df0a7f806e52d630df',
    messagingSenderId: '179711894926',
    projectId: 'hww7-d403c',
    authDomain: 'hww7-d403c.firebaseapp.com',
    storageBucket: 'hww7-d403c.firebasestorage.app',
    measurementId: 'G-D5S7TPP5FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8kf61ke_zX_qm2oKiSgfq4d_pZcaEDpo',
    appId: '1:179711894926:android:2f8544385dcb518fd630df',
    messagingSenderId: '179711894926',
    projectId: 'hww7-d403c',
    storageBucket: 'hww7-d403c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYkRWK_R7Ayl2mQ-_iuUC_7d-F4GgIvuk',
    appId: '1:179711894926:ios:724502ac8c39c0c8d630df',
    messagingSenderId: '179711894926',
    projectId: 'hww7-d403c',
    storageBucket: 'hww7-d403c.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYkRWK_R7Ayl2mQ-_iuUC_7d-F4GgIvuk',
    appId: '1:179711894926:ios:724502ac8c39c0c8d630df',
    messagingSenderId: '179711894926',
    projectId: 'hww7-d403c',
    storageBucket: 'hww7-d403c.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ0WmxnsLvgGoFhVmviIm4iDZsWEdYrJ4',
    appId: '1:179711894926:web:2bdeb73366c8fdaad630df',
    messagingSenderId: '179711894926',
    projectId: 'hww7-d403c',
    authDomain: 'hww7-d403c.firebaseapp.com',
    storageBucket: 'hww7-d403c.firebasestorage.app',
    measurementId: 'G-8B4ZEF0TG1',
  );
}
